// Generates src/data/cities.ts from Natural Earth (public domain).
//
// Run once with `npm run generate:cities`, then commit the output. The game
// never geocodes at runtime: a fixed, reviewed list keeps pairing predictable
// and means there is no extra third-party request to fail in production.
//
// Inputs (committed in scripts/data/ so the script is reproducible offline):
//   ne_110m_populated_places_simple.geojson  - city names + coordinates
//   ne_110m_admin_0_countries.geojson        - supplies each country's continent
// Source: https://github.com/nvkelso/natural-earth-vector

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const read = (name) =>
  JSON.parse(readFileSync(fileURLToPath(new URL(`./data/${name}`, import.meta.url)), 'utf8'))

const places = read('ne_110m_populated_places_simple.geojson').features.map((f) => f.properties)
const countries = read('ne_110m_admin_0_countries.geojson').features.map((f) => f.properties)

const MIN_POPULATION = 500_000

// Capitals below the population cutoff that we keep anyway. Without them
// Oceania, the Pacific, and a few other regions would have almost no cities.
const ALWAYS_INCLUDE = new Set([
  'Wellington',
  'Canberra',
  'Port Moresby',
  'Suva',
  'Honiara',
  'Port Vila',
  'Reykjavík',
  'Nassau',
  'Port Louis',
  'Malé',
  'Ulaanbaatar',
  'Windhoek',
  'Georgetown',
  'Paramaribo',
  'Tallinn',
  'Ljubljana',
  'Bern',
  'Port-of-Spain',
])

// Natural Earth's 110m country layer omits some tiny states, so a few cities
// have no continent in the join. Listed explicitly so a new gap fails loudly.
const CONTINENT_OVERRIDES = {
  SGP: 'Asia',
  HKG: 'Asia',
  MUS: 'Africa',
  MDV: 'Asia',
  BHR: 'Asia',
  BRB: 'North America',
  TTO: 'North America',
  ISL: 'Europe',
}

// Natural Earth uses formal names; players expect the everyday ones.
const COUNTRY_NAMES = {
  'United States of America': 'United States',
  'United Republic of Tanzania': 'Tanzania',
  'Republic of Serbia': 'Serbia',
  'Republic of the Congo': 'Congo',
  'Democratic Republic of the Congo': 'DR Congo',
  'Ivory Coast': "Côte d'Ivoire",
  'The Bahamas': 'Bahamas',
  'Congo (Brazzaville)': 'Republic of the Congo',
  'Congo (Kinshasa)': 'DR Congo',
  'Hong Kong S.A.R.': 'Hong Kong',
}
const CITY_NAMES = {
  'Washington,  D.C.': 'Washington, D.C.',
  'Nur-Sultan': 'Astana',
  'København': 'Copenhagen',
  'Ōsaka': 'Osaka',
  'Ürümqi': 'Urumqi',
}
// Natural Earth lists these but they are alternates of a city we already have.
const EXCLUDE = new Set(['Kyoto', 'Tel Aviv', 'Sri Jayawardenepura Kotte', 'Baguio', 'Valparaíso'])

const continentByCode = new Map()
for (const c of countries) {
  continentByCode.set(c.ADM0_A3, c.CONTINENT)
  continentByCode.set(c.ISO_A3, c.CONTINENT)
}

const slug = (s) =>
  s
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')

const cities = []
for (const p of places) {
  if (EXCLUDE.has(p.name)) continue
  if (p.pop_max < MIN_POPULATION && !ALWAYS_INCLUDE.has(p.name)) continue

  const continent = continentByCode.get(p.adm0_a3) ?? CONTINENT_OVERRIDES[p.adm0_a3]
  if (!continent) throw new Error(`No continent for ${p.name} (${p.adm0_a3}); add an override`)

  const name = CITY_NAMES[p.name] ?? p.name
  cities.push({
    id: slug(name),
    name,
    country: COUNTRY_NAMES[p.adm0name] ?? p.adm0name,
    lat: Number(p.latitude.toFixed(3)),
    lon: Number(p.longitude.toFixed(3)),
    region: continent,
  })
}

cities.sort((a, b) => a.name.localeCompare(b.name))

const ids = new Set(cities.map((c) => c.id))
if (ids.size !== cities.length) throw new Error('Duplicate city ids')

const rows = cities.map((c) => `  ${JSON.stringify(c)},`).join('\n')
const out = `// GENERATED by scripts/generate-cities.mjs from Natural Earth - do not edit by hand.
import type { City } from '../types'

export const CITIES: readonly City[] = [
${rows}
]
`
writeFileSync(fileURLToPath(new URL('../src/data/cities.ts', import.meta.url)), out)

const byRegion = {}
for (const c of cities) byRegion[c.region] = (byRegion[c.region] ?? 0) + 1
console.log(`Wrote ${cities.length} cities`, byRegion)
const south = cities.filter((c) => c.lat < 0).length
console.log(`Southern hemisphere: ${south}`)
